/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frame.java
 *
 * Created on 23-abr-2012, 0:09:39
 */
package archivos;


import java.awt.BorderLayout;
import java.io.File;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;


/**
 *
 * @author Alberto
 */
public final class Frame extends javax.swing.JFrame { 

    /** Creates new form Frame */
    
    static ArchivoBinario archivo;
    static String namearchivo="Binariote.txt";  
    JScrollPane scroll;
    static GenerarYActualizarTabla tabla;
    public Frame() {
       archivo=new ArchivoBinario("Binariote.txt");
       //archivo.CrearArchivo();
       this.setTitle("Base De Datos con Archivos");
       this.setLocation(300,200); 
       this.setResizable(false);
       /*dtm=new DefaultTableModel();
       tabla=new JTable(dtm);
       dtm.setColumnIdentifiers(titulos);//asigna mi Cadena a la primera Columna
       tabla.setEnabled(false);
       scroll=new JScrollPane(tabla);
       */
       tabla=new GenerarYActualizarTabla();
       add(tabla,BorderLayout.CENTER);
       tabla.setBounds(45, 370, 610, 160);
       
        Tabla(namearchivo);
        initComponents();
        
        
        
    }
    public static void Tabla(String namearchivod){
        namearchivo=namearchivod;
        tabla.ActualizaTabla(archivo.ListaPersonas());
        System.out.println("Hola");
        archivo.LeerArchivo();
    }
    
    /*
     
     * public JScrollPane Tabla()
       {
        dtm=new DefaultTableModel();
        tabla=new JTable(dtm);
        dtm.setColumnIdentifiers(titulos);//asigna mi Cadena a la primera Columna
        tabla.setEnabled(false);
        scroll=new JScrollPane(tabla);
        
        return scroll;
        
       }*/
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jpanelingresodatos = new javax.swing.JPanel();
        jlabelname = new javax.swing.JLabel();
        jlabelcodigo = new javax.swing.JLabel();
        jlabelfono = new javax.swing.JLabel();
        jlabelsueldo = new javax.swing.JLabel();
        jTextFieldcodigo = new javax.swing.JTextField();
        jTextFieldfono = new javax.swing.JTextField();
        jTextFieldsueldo = new javax.swing.JTextField();
        jButtonregistrar = new javax.swing.JButton();
        jTextFieldname1 = new javax.swing.JTextField();
        ComboBoxtipo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanelopciones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldbuscarcodigo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonEditar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jpanelingresodatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese Datos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jpanelingresodatos.setLayout(null);

        jlabelname.setText("Nombre     :");
        jpanelingresodatos.add(jlabelname);
        jlabelname.setBounds(20, 30, 70, 20);

        jlabelcodigo.setText("Codigo      :");
        jpanelingresodatos.add(jlabelcodigo);
        jlabelcodigo.setBounds(20, 70, 70, 20);

        jlabelfono.setText("Telefono   :");
        jpanelingresodatos.add(jlabelfono);
        jlabelfono.setBounds(20, 110, 80, 14);

        jlabelsueldo.setText("Sueldo      :");
        jpanelingresodatos.add(jlabelsueldo);
        jlabelsueldo.setBounds(20, 144, 70, 20);
        jpanelingresodatos.add(jTextFieldcodigo);
        jTextFieldcodigo.setBounds(100, 70, 140, 20);
        jpanelingresodatos.add(jTextFieldfono);
        jTextFieldfono.setBounds(100, 100, 140, 20);
        jpanelingresodatos.add(jTextFieldsueldo);
        jTextFieldsueldo.setBounds(100, 140, 140, 20);

        jButtonregistrar.setText("Registrar");
        jButtonregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonregistrarActionPerformed(evt);
            }
        });
        jpanelingresodatos.add(jButtonregistrar);
        jButtonregistrar.setBounds(80, 280, 150, 30);
        jpanelingresodatos.add(jTextFieldname1);
        jTextFieldname1.setBounds(100, 30, 140, 20);

        ComboBoxtipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Contratado", "Planilla", "Diario", "Interdiario" }));
        ComboBoxtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxtipoActionPerformed(evt);
            }
        });
        jpanelingresodatos.add(ComboBoxtipo);
        ComboBoxtipo.setBounds(100, 180, 140, 20);

        jLabel3.setText("Tipo         :");
        jpanelingresodatos.add(jLabel3);
        jLabel3.setBounds(20, 180, 60, 20);

        jLabel4.setText("Turno      :");
        jpanelingresodatos.add(jLabel4);
        jLabel4.setBounds(20, 230, 70, 14);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Mañana");
        jpanelingresodatos.add(jRadioButton1);
        jRadioButton1.setBounds(90, 230, 70, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Tarde");
        jpanelingresodatos.add(jRadioButton2);
        jRadioButton2.setBounds(160, 230, 60, 23);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Noche");
        jpanelingresodatos.add(jRadioButton3);
        jRadioButton3.setBounds(220, 230, 55, 23);

        jPanel2.add(jpanelingresodatos);
        jpanelingresodatos.setBounds(40, 20, 310, 340);

        jPanelopciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jPanelopciones.setLayout(null);

        jLabel1.setText("Buscar por Codigo :");
        jPanelopciones.add(jLabel1);
        jLabel1.setBounds(10, 30, 120, 30);
        jPanelopciones.add(jTextFieldbuscarcodigo);
        jTextFieldbuscarcodigo.setBounds(110, 40, 140, 20);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelopciones.add(jButton1);
        jButton1.setBounds(80, 80, 150, 30);

        jLabel2.setText("Editar Datos Por Campos  :");
        jPanelopciones.add(jLabel2);
        jLabel2.setBounds(10, 120, 150, 30);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanelopciones.add(jButtonEditar);
        jButtonEditar.setBounds(80, 170, 150, 30);

        jPanel2.add(jPanelopciones);
        jPanelopciones.setBounds(380, 20, 270, 210);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eliminar Registro", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));

        jButton2.setText("Eliminar");

        jTextField1.setEditable(false);
        jTextField1.setText("       Escoga Registro a Eliminar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(380, 250, 270, 110);

        jPanel2.setBounds(0, -1, 680, 540);
        jDesktopPane1.add(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu3.setText("Archivo");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Nuevo Archivo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Cargar Archivo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Eliminar Archivo");
        jMenu3.add(jMenuItem2);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Ubicacion");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);
        jMenu3.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Ver");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Ver Tabla");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
   EditarCampos editar=new EditarCampos();
   
   editar.show();
}//GEN-LAST:event_jButtonEditarActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//Evento para buscar por codigo
    if( !"".equals(jTextFieldbuscarcodigo.getText())){
    Persona pe=archivo.BuscarCodigo(jTextFieldbuscarcodigo.getText());
    
      if(pe!=null){
       JOptionPane.showMessageDialog(this,"\n\t\tPersona Encontrada\n "+"\n\n\tCodigo  :       "+pe.getCodigo()+"\n\n\tNombre  :     "
            +pe.getNombre()+"\n\n\tTelefono  :     "
            +pe.getTelefono()+"\n\n\tSueldo   :       "+pe.getSueldo()+"\n");
            
       }
       else
        JOptionPane.showMessageDialog(this,"\n\tNo se Encuentra el Codigo : "+ jTextFieldbuscarcodigo.getText()+" en la Base de Datos\n");
   }
   else
   JOptionPane.showMessageDialog(this,"\n\tEscriba Un Codigo A Buscar\n");     
    
   jTextFieldbuscarcodigo.setText("");
}//GEN-LAST:event_jButton1ActionPerformed

private void jButtonregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonregistrarActionPerformed
     
    //se vuelve a llenar todo de nuevo el arraylist, deberia solo agregarse 
    //deberia ser una variable global y deberia inicializarse en el constructor
    
    List<Persona> personactual=new <Persona>ArrayList();
        List<Persona> personal=null;
         
         
        
        try{
         FileInputStream fis=new FileInputStream(namearchivo);
         ObjectInputStream ois=new ObjectInputStream(fis);
         personal=(ArrayList<Persona>)ois.readObject();
         if(personal!=null){
            for(Persona pe:personal){
                  personactual.add(pe);
           }
             personactual.add(new Persona(jTextFieldname1.getText(),jTextFieldcodigo.getText()
                     ,jTextFieldfono.getText(),Integer.parseInt(jTextFieldsueldo.getText())));
                  
                   
                    archivo.EscribirArchivo(personactual);
                    tabla.ActualizaTabla(archivo.ListaPersonas());
                    JOptionPane.showMessageDialog(this,"Registro copiado Exitosamente al Archivo\n\tNombre : "+jTextFieldname1.getText()+"\n\tCodigo : "
                            +jTextFieldcodigo.getText()+"\n\tTelefono : "+jTextFieldfono.getText()+"\n\tSueldo : "
                            +Integer.parseInt(jTextFieldsueldo.getText()));
                   jTextFieldname1.setText(""); 
                   jTextFieldcodigo.setText("");
                   jTextFieldfono.setText("");
                   jTextFieldsueldo.setText("");
         }
     
   
     
       //Agregar elementos
        else
                System.out.println("Archivo vacio");
        fis.close();
        ois.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Complete Los Campos");
            System.out.println("ERROR Al Agregar");
      }   
}//GEN-LAST:event_jButtonregistrarActionPerformed

private void ComboBoxtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxtipoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_ComboBoxtipoActionPerformed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       this.namearchivo=archivo.AsignarArchivo();
       tabla.ActualizaTabla(archivo.ListaPersonas());
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
// TODO add your handling code here:
   System.exit(1);
}//GEN-LAST:event_jMenuItem3ActionPerformed


private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
  // TODO add your handling code here:
  //codigo para ver la tabla
  JFrame fra=new JFrame();
  GenerarYActualizarTabla table=new GenerarYActualizarTabla();
  fra.setSize(800,400);
  fra.setLocation(250,370);
  fra.add(table,BorderLayout.CENTER);
  table.ActualizaTabla(archivo.ListaPersonas());
  fra.setTitle("Registro de Empleados");
  fra.setVisible(true);
 

}//GEN-LAST:event_jMenuItem4ActionPerformed

private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
   //Caracteristicas del Archivo
           archivo.Archivo();
          
    
}//GEN-LAST:event_jMenuItem5ActionPerformed

private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
     NuevoArchivo nuevoarchivo=new NuevoArchivo();
     nuevoarchivo.setVisible(true);
     //String nuevoarchivo=JOptionPane.showInputDialog(this,"Nombre Del Archivo A Crear");
    //String name=JOptionPane.showInputDialog(this,"Ingrese Nombre","CREAR PRIMER REGISTRO ",JOptionPane.INFORMATION_MESSAGE);
     //String codigo=JOptionPane.showInputDialog(this,"Ingrese Codigo","CREAR PRIMER REGISTRO ",JOptionPane.INFORMATION_MESSAGE);
     //String Telefono=JOptionPane.showInputDialog(this,"Ingrese Telefono","CREAR PRIMER REGISTRO ",JOptionPane.INFORMATION_MESSAGE);
     //String Sueldo=JOptionPane.showInputDialog(this,"Ingrese Sueldo","CREAR PRIMER REGISTRO ",JOptionPane.INFORMATION_MESSAGE);
     
     //System.out.println(name+nuevoarchivo+codigo+Telefono+Sueldo);
    /*
     ArchivoBinario nuevo=new ArchivoBinario(nuevoarchivo+".txt"); 
     nuevo.CrearArchivo();
     nuevo.LLenarDatos();*/
}//GEN-LAST:event_jMenuItem6ActionPerformed
 


/*   public void ActualizarTabla(){
   
    List<Persona> personas=null;
        try{
            dtm.setRowCount(0); //limpio mi tabla y la vuelvo a llenar
            dtm.setColumnCount(0);
            dtm.setColumnIdentifiers(titulos);
          
            FileInputStream fis=new FileInputStream(namearchivo);//f="Binario.txt"
            ObjectInputStream ois=new ObjectInputStream(fis);
            personas=(ArrayList<Persona>)ois.readObject();
            if(personas!=null){
              for(Persona p:personas){
                  Object[] fila={p.getNombre(),p.getCodigo(),p.getTelefono(),p.getSueldo()};
                  dtm.addRow(fila);
                  
              }
           }
           else
                System.out.println("No hay registros");
        
           fis.close();
           ois.close();
           
        }catch(Exception ex){
            System.out.println("Error de lectura");
            JOptionPane.showMessageDialog(null,"ERROR DE LECTURA,CARGAR OTRO ARCHIVO","Error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
}  */

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Frame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxtipo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonregistrar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelopciones;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldbuscarcodigo;
    private javax.swing.JTextField jTextFieldcodigo;
    private javax.swing.JTextField jTextFieldfono;
    private javax.swing.JTextField jTextFieldname1;
    private javax.swing.JTextField jTextFieldsueldo;
    private javax.swing.JLabel jlabelcodigo;
    private javax.swing.JLabel jlabelfono;
    private javax.swing.JLabel jlabelname;
    private javax.swing.JLabel jlabelsueldo;
    private javax.swing.JPanel jpanelingresodatos;
    // End of variables declaration//GEN-END:variables

   
}
